build: &build
  steps:
    - checkout
    - type: cache-restore
      name: Restore bundle cache
      key: chef-v1-{{ .Environment.CIRCLE_BUILD_IMAGE }}-bundle-{{ checksum "Gemfile.lock" }}
    - run:
        name: Bundle Install
        command: bundle install --path vendor/bundle --without ci docgen guard integration maintenance omnibus_package --frozen
    - type: cache-save
      name: Save bundle cache
      key: chef-v1-{{ .Environment.CIRCLE_BUILD_IMAGE }}-bundle-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
    - type: shell
      name: chef-config rspec
      command: |
        mkdir -p test_results
        sudo -E $(which bundle) exec rake component_specs
    - type: shell
      name: chef rspec
      command: |
        mkdir -p test_results
        sudo -E $(which bundle) exec rake spec
    # Save test results for timing analysis
    - store_test_results:
        path: test_results

version: 2
jobs:
  ruby_2_4:
    <<: *build
    docker:
      - image: circleci/ruby:2.4
  ruby_2_5:
    <<: *build
    docker:
      - image: circleci/ruby:2.5
  chefstyle:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - type: cache-restore
        name: Restore bundle cache
        key: chef-v1-chefstyle-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle --without ci docgen guard integration maintenance omnibus_package --frozen
      - type: cache-save
        name: Save bundle cache
        key: chef-v1-chefstyle-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: ChefStyle
          command: bundle exec rake style
workflows:
  version: 2
  test:
    jobs:
      - ruby_2_4
      - ruby_2_5
      - chefstyle
